c/crossmemory.c

Signed-off-by: Irek Fakhrutdinov <ifakhrutdinov@rocketsoftware.com>

Fix incorrect cross-memory service ID checks

---

c/httpfileservice.c
c/json.c
c/zosfile.c
h/httpfileservice.h
h/json.h
h/unixfile.h

Added more functionality for uploading files to USS

---

c/dataservice.c
c/utils.c
h/utils.h

New services were being made as insecure unless otherwise stated, so this does the opposite: opt-out rather than opt-in.
lastIndexOf wasnt working for me because I had a const char. Shouldn't it be a const?

Const and security

---

h/zos.h

Map additional ECVT fields.
Signed-off-by: Irek Fakhrutdinov <ifakhrutdinov@rocketsoftware.com>

Extend ECVT mapping

---

h/json.h

make json.h self contained

---

c/http.c

EAGAIN and EWOULDBLOCK should be checked.

---

c/dataservice.c

DLL's can now reside in respective plugin folders.

---

c/alloc.c
h/alloc.h

A prerequisite for https://github.com/zowe/zss/pull/32.

Add 64-bit allocators

---

c/json.c
h/json.h

Multipart string support in the json printer

---

c/datasetjson.c
h/datasetjson.h

Make zowe-common-c compatible with new dataset API

---

c/datasetjson.c

Bugfix for name of default archived volume

---

c/utils.c
c/zos.c
h/utils.h
h/zos.h

Added several utilities to assist in Top Secret security API.

---

c/httpfileservice.c

Fixed a bug where new directories or files would have no permissions

---

c/httpfileservice.c
c/zosfile.c
h/charsets.h
h/httpfileservice.h
h/unixfile.h

Refactored several core components of the unix file api.

---

c/httpserver.c

Allow basic auth for login

---

jwt/jwt/jwt.h

Fix the include path in the header

---

c/as.c
c/pause-element.c
c/pc.c
c/shrmem64.c
h/as.h
h/pause-element.h
h/pc.h
h/shrmem64.h

The following wrappers have been added:
* Address space management
* Pause elements
* Program calls
* 64-bit shared memory objects

PC, paulse elements, A/S and shared memory objects wrappers for the ZIS AUX projects.

---

c/datasetjson.c
h/datasetjson.h

Signed-off-by: Suneeth Keerthy <skeerthy@rocketsoftware.com>

Fix for deleting nonexisting member

---

c/cmutils.c
c/collections.c
h/cmutils.h
h/collections.h

This pull request add the following features:
* Ability to use the lock-free queue intrusively which allows a more flexible storage management on the user's side
* Functions to copy to/from foreign address space using destination/source keys and ALETs

Expose additional functionality in collections and cross-memory

---

h/bpxnet.h

Add EADDRINUSE

---

h/httpserver.h

https://github.com/zowe/zss/pull/173

added hashtable to httpserver struct

---

c/zos.c
h/zos.h

https://github.com/zowe/zss/pull/175

added a new option for saf auth to hide logs

---

c/bpxrawfd.c
c/cmutils.c
c/icsf.c
h/shrmem64.h

These are the fixes that I found while working on Zowe ZSS 64 that were wrong for all users, 31 bit or not.

Zowe112 fixes 1

---

c/httpserver.c

Signed-off-by: Akayeshmantha <akayeshmantha@apache.org>

fix issue to handle text file names starts with ".".

---

c/httpserver.c

autobuild showed failure, so fixed the cause.

Small syntax fix

---

c/httpfileservice.c
c/httpserver.c
c/utils.c
c/zosaccounts.c
h/utils.h
h/zosaccounts.h

This PR includes `owner` and `group` fields into the Unixfile metadata and directory listing(JSON).

Include owner and group into Unixfile metadata response and directory listing

---

c/bpxskt.c
c/httpserver.c
c/socketmgmt.c
c/tls.c
h/bpxnet.h
h/httpserver.h
h/tls.h

TLS Support for HTTP Server using gskit library.

TLS Support

---

c/discovery.c

https://github.com/zowe/zowe-common-c/pull/187 but for staging.

Reintroduce trace conditionals to use of dumpbuffer

---

c/httpclient.c
h/httpclient.h

Depends on:
- https://github.com/zowe/zowe-common-c/pull/178
- https://github.com/zowe/zowe-common-c/pull/179

Secure HTTP Client

---

c/dataservice.c
c/storage.c
c/storage_mem.c
h/dataservice.h
h/storage.h

Preparation work before connecting ZSS and Cashing Service in APIML (https://docs.google.com/document/d/1Z8T1mq7MRYzxREL2pf1zTlj0tP7fqaR2ba31TZHX0Qw/edit?usp=sharing)
The PR 
- defines the shape of the API
- adds in-memory implementation for the API
Related to https://github.com/zowe/api-layer/issues/890.
Test program for Memory Storage is embedded into the source code.

Make zss storage API

---

h/cmutils.h
h/idcams.h

This pull-requests adds more documentation to the common code. Hopefully this will clarify some of the more complicated aspects of z/OS.

Documentation for IDCAMS and cross-memory utils.

---

h/httpserver.h

Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>

Updated header file to include user & group hash table

---

c/httpserver.c

Adding PRs https://github.com/zowe/zowe-common-c/pull/201 and https://github.com/zowe/zowe-common-c/pull/200 to staging

Memory bugfixes for staging branch

---

c/httpserver.c

Uncommenting out a temporary fix.

uncommenting out code

---

h/tls.h

Cipher suite definitions

---

c/datasetjson.c

Currently we skips empty record in DS contents API. This PR fixes the bug.
Merge together with: https://github.com/zowe/zss/pull/286

Handle empty records during dataset reading

---

c/httpserver.c

Handle files with unknown extension

---

c/dataservice.c
h/dataservice.h

Expose both local and remote storage apis to zss dataservices

Expose both storage apis to zss dataservices

---

CHANGELOG.md
c/dataservice.c

This PR just fixes some logging as requested in https://github.com/zowe/zss/issues/277
Also, it attempts to log success.

Fix messages about dll loading

---

c/httpserver.c
h/httpserver.h

RBAC code cleanup

---

c/httpserver.c

Fix abend when checking session validity

---

c/httpserver.c

#229 is still awaiting testing, reverting accidental merge.

Reverting 229

---

c/httpserver.c
h/httpserver.h

Add return code for registerHttpAuthorizationHandler

---

c/httpserver.c
h/httpserver.h

Rename AuthorizationHandler to HttpAuthorize

---

c/httpserver.c

This PR removes code that temporary disabled impersonation.

Remove code that temporary disabled impersonation

---

c/datasetjson.c

Signed-off-by: Aditya Ranshinge <aranshinge@rocketsoftware.com>
Identified type of RECFM. 
If RECFM is of type U then returned valid status code.

Fixed update of Undefined type of RECFM dataset

---

c/datasetjson.c

Builds upon https://github.com/zowe/zowe-common-c/pull/247 to implement writing.
Details in https://github.com/zowe/zss/pull/355

Optimistic-locking dataset write with etag

---

c/discovery.c
c/pause-element.c
c/radmin.c
h/pause-element.h
h/radmin.h
h/zos.h

**Note: my unit tests have passed but I'm still verifying these changes with ZIS**

Avoid allocating storage in radmin

---

c/httpserver.c
h/httpserver.h
jwt/jwt/jwt.c
jwt/jwt/jwt.h

The PR adds an ability to provide a callback function for JWT signature verification.
This PR is a prerequisite for https://github.com/zowe/zss/pull/363

JWT verification using JWK
