c/datasetjson.c, c/httpserver.c, c/jcsi.c
1. httpserver uses an ASCII string as an EBCDIC string
2. Multiple bugfixes in csi code:
-  No need to allocate DSCB1 buffers on the heap
-  No need to check a struct field for NULL (entry->name) - it can't be NULL
-  Use jsonAddUnterminatedString for space padded unterminated strings
-  Fix a double free - dsn pointer derived from either an SLH or a local buffer
=> Remove use of ASCII as EBCDIC; fix unterminated string handling

c/crossmemory.c, h/crossmemory.h
It is unsafe to call CSVDYLPA DELETE. This feature will only be
available in dev mode. In release mode, we'll never attempt to
delete the server module from LPA, and will just abandon it if
the module timestamp doesn't match the timestamp of the private
storage module.
Signed-off-by: Irek Fakhrutdinov <ifakhrutdinov@rocketsoftware.com>
=> Discard LPA module if a different version has been detected.

c/httpserver.c, h/httpserver.h
Because the ZSS server doesnt implement TLS of its own, if we determine that we're in a case where it is important (say, listening on external interface), then we want to alert the admin if TLS was needed but not being used. When using AT-TLS, this warning should not be seen.
=> Warn if need TLS and TLS isnt being used

c/httpserver.c
The following changes have been made:
* Return 403 if impersonation hasn't been successful
* Print an error message with possible causes of the unsuccessful impersonation
* Minor refactoring to make the impersonation logic clearer when handling a request
=> Service must fail if impersonation has not been successful

c/dataservice.c, c/datasetjson.c, c/httpfileservice.c, c/httpserver.c, h/dataservice.h, h/httpserver.h
Implements https://github.com/zowe/zss/issues/11
Accomplished by adding a utility function for calling to set up some default headers. I put this in dataservice.h since its most likely to be used by dataservices. Couldn't think of a better place.
Aside from adding headers instructing receivers not to cache the results, this change also unifies the content type of json. The majority of our code used MIME "text/json", but the official MIME type is "application/json", so hopefully this improves compatibility in edge cases.
=> Add convenience function to roll up headers used for REST JSON responses

h/socketmgmt.h, h/stcbase.h
While working on a plugin, it was discovered that ```stcbase.h``` and ```socketmgmt.h``` could not be included by themselves. This fix adds includes headers so that ```stcbase.h``` and ```socketmgmt.h``` don't depend on the order they're included or on what other header are included (or not) before them.
=> Make stcbase.h and socketmgmt.h self-contained

c/crossmemory.c, h/crossmemory.h
The pull-request adds a cross-memory core service that can be used to retrieve the server status. This initial version includes basic information only (call RC, description).
Other changes:
* Check the server name for NULL in cmsCallService
* Comment about a flaw in the cmsGetGlobalArea implementation
**It is a prerequisite for https://github.com/zowe/zss/issues/8**
=> Add a core service that returns status information.

c/zos.c, h/zos.h
=> correct function prototypes: use the correct C99 form `void foo(void)`

c/fdpoll.c, c/http.c, h/fdpoll.h
This should help the performance of downloading files by eliminating the constant failed BPXWRT calls when attemping to write to a full socket.
=> Add BPXPOL to open-source library; poll on socket before BPXWRT

h/crossmemory.h, h/isgenq.h
- IS_ISGENQ_LOCK_OBTAINED macro
- Workaround for a bug in the Metal headers
First part of what used to be https://github.com/zowe/zowe-common-c/pull/29
=> ISGENQ wrapper fixes/improvements:

c/le.c
There is an OS version check that prevents the LE related code from running on an unsupported z/OS version. This protects the code from using CAA incorrectly in case it gets updates with the OS. The current version is 2.3, this pull-request updates the corresponding ```#define``` to use the 2.4 value.
Fixes zowe/zss#15
=> Update the z/OS version check to support z/OS 2.4

c/timeutls.c
The output variable was passed to the asm block as an input variable
instead, thus with some compile options (not always!) the function
failed to produce an output.
Second part of what used to be https://github.com/zowe/zowe-common-c/pull/29
=> Fix variable passing in getSTCK() and getSTCKU()

c/datasetjson.c
While reading in lines from the dataset, the function streamDataset() did not check if an entry was of size 0 (indicating end of file). By adding a conditional check, the extra blank line is no longer printed.
=> Dataset eof bug

c/httpserver.c
Calling get on a directory the user does not have permission for returns the correct status and error message.
Signed-off-by: E Kirschner <ekirschner@rocketsoftware.com>
=> Bugfix forbidden returns 200 OK

c/httpserver.c, c/zosfile.c, h/unixfile.h
Added function to not follow symbolic link. Called "symbolicFileInfo"
=> Added function to not follow symbolic links

c/httpserver.c
This pull-request fixes an incorrect ```if``` statement that causes a file descriptor leak.
=> File API descriptor leak

c/alloc.c, c/json.c, h/alloc.h
The buffer used to be fixed size. Now it grows dynamically up to a
compile time specified limit.
=> Dynaically grow the JSON tokenizer buffer

c/alloc.c, h/alloc.h
The header used `int32_t` but didn't include stdint or zowetypes.
That broke the compile for some files which either didn't include 
stdint/zowetypes, or included alloc.h before stdint/zowetypes.
Since `int32_t` and `int` are abosultely the same in all of our use
cases, the simper thing is to change the types to int (like the
rest of the functions in the file)
=> change `int32_t` to `int` in `safeRealloc()`

c/json.c, h/json.h
Currently, in order to print a valid JSON string it must be null-terminated. This pull request adds a new function that can print unterminated JSON strings.
=> Add a function for printing unterminated JSON strings

c/datasetjson.c, c/dynalloc.c, c/httpserver.c, h/dynalloc.h, h/httpserver.h
1. Detect if the volume we're accessing a dataset on is unavailable using UCB scan.
2. Prevent memory leaks when using ```fldata```
Fixes: zowe/zss#50
=> Check if volumes are available when using the dataset API

c/collections.c
Fix a memory leak in htDestroy
The description of ```htDestroy``` says the following:
```
/**
*   \brief This is the destructor for the hashtable.
*
*   This will reclaim the memory of the hashtable.   If keyReclaimer and valueReclaimer have been supplied
*   in the constructor they will be called on each key and value.
*/
```
The actual code does not call the key and value reclaimer functions. This pull-request adds those calls to  ```htDestroy```
=> Fix a memory leak in htDestroy

c/httpfileservice.c
- Reorganized logic to use boolean better and changed a 500 to a 400 to better differentiate a probable permission problem from a general server error.
PR 2 of 2
PR 1 https://github.com/zowe/zss/pull/93
Signed-off-by: Leanid Astrakou <lastrakou@rocketsoftware.com>
=> Fixed bool function --> int function and added better response returns

c/recovery.c, h/recovery.h
In an environment where an application creates linkage stack entries after a ```recoveryEstablishRouter``` call, the recovery exit will restore the wrong linkage stack entry upon retry. That will lead to the code and linkage stack to be out-of-sync.
This pull request tracks linkage stack entries using IEALSQRY, and uses those values during the retry phase.
[Details from IBM](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.ieaa600/example.htm)
=> Use IEALSQRY to get the correct linkage stack value for retry calls

c/crossmemory.c, h/crossmemory.h
The purpose of this enhancement is to allow calling cross-memory servers from system exits.
A new public function has been added that allows passing flags to cross-memory calls. At the moment there is only one flag - the "skip SAF check" flag. The flags makes it possible to skip the SAF check if the caller is either in:
* Supervisor state
* System key (key 0-7)
If the caller is in neither of those states, the flag is ignored.
=> Add the ability to skip SAF check for privileged callers of a cross memory server.

c/recovery.c, h/recovery.h
Changes:
* Use FRR when running under an SRB
* Bypass the SDWA check under an SRB
* Use the FRR exit key when accessing SDWA field (to prevent 0C4 when
SDWA is fetch protected)
* Tell SETRP to restore R15 as this behavior is different from ESTAE
* Verify that the state structure after is valid we've retried
* Save and restore the caller's key in recoveryPush - SETRP restores the
key used at the time of SETFRR which may be different from what we want
* Use better names for the labels in the recovery push asm
=> SRB support in the recovery facility

c/httpfileservice.c, c/zosfile.c
For symbolic links, the fileInfo functions returns the stats of the file the link is pointing, not the status of the link itself.  Place in additional calls to symbolicFileInfo to obtain this  information.
=> Link delete

c/charsets.c, c/httpfileservice.c, c/zosfile.c
Signed-off-by: Steven Bollinger <sbollinger@rocketsoftware.com>
Allow ISO8859-1 along with ISO-8859-1.
Make all file encoding case insensitive.
=> Unixfile/contents:  Allow ISO8859-1 encoding

c/zosfile.c
Signed-off-by: Steven Bollinger <sbollinger@rocketsoftware.com>
=> Remove reference to createUnixDirectory in zosfile.c

c/zos.c, h/zos.h
The following new functions has been added:
* A function to test whether the caller is running in SRB
* A function to test whether the caller is in cross-memory mode
* A function to test whether the caller is holding a CPU, CMS, CML or local lock
=> Add helper functions to test caller's environment

c/crossmemory.c, h/crossmemory.h
The pull-request required the changes from #118 and #120 . When reviewing the code, please disregard the following files:
* zowe-common-c/c/cmutils.c
* zowe-common-c/c/collections.c
* zowe-common-c/c/recovery.c
* zowe-common-c/h/cellpool.h
* zowe-common-c/h/cmutils.h
* zowe-common-c/h/collections.h
* zowe-common-c/h/recovery.h
**Files to be reviewed in this pull-request**:
* zowe-common-c/c/crossmemory.c
* zowe-common-c/h/crossmemory.h
Due to the need to support locked callers in PC-ss, the cross-memory code has been changed to use cell pool based recovery and cell pool based PC-ss stack storage. Additionally, the message service has also been changed to use cell pool for its message queue.
* To support cell pool stack storage, the cross memory server allocates a cell pool upon start up. …
=> Support of locked callers in cross-memory

c/bpxskt.c, c/dataservice.c
Before:
```
reading server settings from /u/tsspg/bt/zlux/zlux-app-server/bin/../deploy/instance/ZLUX/serverConfig/zluxserver.json
productDir is '../deploy/product'
siteDir is '../deploy/site'
instanceDir is '../deploy/instance'
groupsDir is '../deploy/instance/groups'
usersDir is '../deploy/instance/users'
pluginsDir is '../deploy/instance/ZLUX/plugins'
Host name is DNS or non-numeric, 0
*** WARNING: Server doesn't implement HTTPS! ***
*** In production only use localhost or 127.0.0.1! Server using: 0.0.0.0 ***
ZSS server settings: address=0.0.0.0, port=12224
Will not accept JWTs: JWT keystore configuration missing
privilegedServerName or env ZWED_privilegedServerName is not specified, or is NULL.
warning: privileged server …
```
=> Use zowelog instead of printf, reduce useless messages

c/crossmemory.c
In case when the cross memory server has not been started in key 4, for
example, not APF authorized, allocate the cell pools in the current key
to prevent SC78-10.
=> Use caller's key when making the msg queue cell pool to prevent SC78.

c/httpserver.c
Previous code prints this line whenever attls is not set up:
`*** WARNING: Connection is insecure! TLS needed but not found on socket. ***`
Let's print it only once every 25 times.
=> Warn less frequently to not fill up log quickly

c/crossmemory.c, h/crossmemory.h
**Overview**
This pull-request adds a new control flag. The flag allows users to enable the LPA dev mode without recompiling the module. In the LPA dev mode, the ZWESIS01 module will always be refreshed at start up and removed from LPA upon termination. This latter should make the memory footprint smaller in a development environment.
Since removing modules from LPA is considered dangerous, a new warning message will be issued to the SYSLOG and SYSPRINT if the new mode is enabled:
```
ZWES0247W Development mode is enabled
```
=> Control LPA dev mode with a run-time option

CHANGELOG.md, c/httpserver.c
For some reason, logConfigureComponent was used when the httpserver loop starts, which is later than some init tasks. Some logs were not shown.
=> use logConfigureComponent upon server init

c/crossmemory.c, h/crossmemory.h
**Overview**
The use of a cross-memory server without REUSASID=YES may result in an ASID shortage. This pull-request adds a check that and prints a warning if the check fails. Additionally, some environment checks have been consolidated into a single function.
=> Check if cross-memory server runs as a reusable address space

c/crossmemory.c, h/crossmemory.h
**Overview**
If the loadmodule has been copied incorrectly to STEPLIB, the z/OS loader will fail to load it. If there is an available copy in LPA it will be used instead. 
The problem with LPA is that the module may not be of the desired version, and any IDENTIFY calls on an LPA module will cause
serious issues. This pull-request ensures that ZWESIS01 comes from private storage.
=> Verify that ZWESIS01 comes from private storage.

c/httpserver.c, h/http.h, h/httpserver.h
This pull-request fixes a bug reported by QA - ZSS must keep the connection if it responses to with 404 to a request with "Connection: Keep-Alive".
The code only handles `Connection: Keep-Alive`, the others "Keep-Alive" properties are ignored.
=> Keep the connection when Keep-Alive is specified.

c/crossmemory.c, h/crossmemory.h
There's been a lot of confusion when users would start ZIS under a user without an OMVS segment and ZIS would silently crash. This pull-request adds an explicit BPX call which should verify if the STC user has an OMVS segment ans is able to perform BPX calls later in the program.
Fixes zowe/zss#189
=> Verify that the STC user has an OMVS segment

c/httpserver.c
The purpose of this PR is to fix various issues when the number in `Content-length` response header mismatches with actual content length. Chunked Transfer Encoding is supposed to solve all the issues.
=> Use Chunked Transfer Encoding for sending Unix files

c/crossmemory.c, h/crossmemory.h
Until now the users of the cross-memory server could only print simple one line messages to the cross-memory server's log and had no ability to print hex dumps. This pull-request adds a new core service and a client wrapper function which allow users to dump private storage inside cross-memory calls.
Limitations:
* The data size is limited to 512 bytes
* The description length is limited to 31 characters
An example of output (the messages with id ZWES0101I, some lines have been removed to keep this block short):
```
DATESTAMP              JOBNAME  ASCB    (ASID) TCB       MSGID     MSGTEXT                                                     
2020/07/23-09:42:34.41 ZWESISIF 00FBBA00(007A) 008F8588  ZWES0001I ZSS Cross-Memory Server starting, version is 1.13.0+20200723 …
```
=> Add a hex dump core service to the cross-memory server.

c/httpserver.c
Add .env mime type, reorg mime types area to have media type detection come last, and common extensions first. Switch common debug printfs to zowelog
=> Add .env mime type, reorg mime types, and more zowelog

c/crossmemory.c
This pull-request fixes the incorrect cross-memory clean up logic when an initialization error occurs.
=> Ensure clean up hook is not called when error

c/crossmemory.c, h/crossmemory.h
The pull-request adds a function which allows reading the cross-memory parameters without requiring authorization if the caller is running in SUP state or system key.
=> Add an unchecked CMS parm function

c/httpserver.c, h/httpserver.h
This PR allows the service to decide how to handle HTTP requests if the user is not authenticated. Example:
```c
void installServerStatusService(HttpServer *server) {
HttpService *httpService = makeGeneratedService("Simple service", "/simple/service/**");
httpService->authType = SERVICE_AUTH_NATIVE_WITH_SESSION_TOKEN;
httpService->authFlags |= SERVICE_AUTH_FLAG_OPTIONAL;
httpService->serviceFunction = serve;
registerHttpService(server, httpService);
}
int serve(HttpService *service, HttpResponse *response) {
int isAuthenticated = response->request->authenticated;
// check if the user is authenticated
//...
}
```
=> Optional authentication for services

c/httpserver.c
This PR will enable force encoding for files.
For a text file to be readable on the client computer, it must be ASCII or UTF8. But a text file on the mainframe might be EBCDIC instead. So it must be converted, and the current code converts AUTOMATICALLY, and sometimes it is wrong.
When it's wrong, we want to tell it to do something we ask for, rather than automatic conversion.
So, we need a parameter to /unixfile API to allow us to specify the source and target encoding. Source=what is on the mainframe, target=what should the user download.
=> Enable force encoding with provided encoding types.

CHANGELOG.md, c/httpserver.c
I was seeing failure to send files over unixfile api when they are dotfiles or untagged. Appears to have been two mistakes: flipped boolean on checking for forced encoding request, and dotPos detection being from the absolute path rather than filename.
Here's my testing that got it working properly again.
```
Processing file=~/zowe-setup-certificates.env
getMimeType2 extension=env, isDotFile=0
Mimetype=text/plain
ccsid=0
Force encoding=
Sending with default conversion between 1047 and 819
completed send
Processing file=~/.Xauthority
getMimeType2 extension=Xauthority, isDotFile=1
Mimetype=text/plain
ccsid=0
Force encoding=
Sending with default conversion between 1047 and 819
completed send
Processing file=~/.tcshrc
getMimeType2 extension=tcshrc, isDotFile=1
Mimetype=text/plain
ccsid=1047 …
```
=> Fix for untagged and dotfiles not being properly sent over rest api

h/httpserver.h
Putting new header int at the end of the struct to be better backward-compatible.
=> Fixing header order

c/zosfile.c
This PR allows to change tag for all files in the directory excluding subdirectories.
For example `POST /unixfile/chtag/u/user/tmp?codeset=1047&type=text&recursive=false` should change tags only for files in `u/user/tmp` without subdirectories
=> Allow to change tag for all files in the directory excluding subdirectories

c/httpserver.c
Disables key behavior of https://github.com/zowe/zowe-common-c/pull/147 while working on a permanent solution.
=> Temporarily disable keep-alive parsing to work-around memory issue

c/httpserver.c, h/httpserver.h
The SLH will become full eventually and crash the server. From evidence of testing, 1000 requests should be plenty and won't crash the server. At some point, we should do timeouts, but for now, at least we can do the right thing for Postman, etc.
=> maximum of 1000 requests to prevent slh from becoming full

c/discovery.c
Logging changes in https://github.com/zowe/zowe-common-c/pull/139 made conditional use of dumpbuffer unconditional.
This sort of info is not needed in most environments, so disabling by default again.
=> Reintroduce trace conditionals to use of dumpbuffer

c/zosaccounts.c, h/zosaccounts.h
The PR adds a new function that gets a list of groups for a user. The function is similar to [getgrouplist](https://man7.org/linux/man-pages/man3/getgrouplist.3.html)
Example of usage:
```C
int count = 0;
int rc = 0;
int returnCode;
int reasonCode;
const char *user = "root";
// obtain group count for user
rc = getGroupList(user, NULL, &count, &returnCode, &reasonCode);
if (rc == -1) {
printf ("failed to obtain group count for user %s\n", user);
exit(EXIT_FAILURE);
}
printf ("found %d groups\n", count);
// allocate array for group list
int *groups = (int*)safeMalloc(sizeof(int) * count, "groups");
// obtain group list
rc = getGroupList(user, groups, &count, &returnCode, &reasonCode);
if (rc == -1) {
printf ("unable to get groups for user %s\n", user);
exit(EXIT_FAILURE);
}
for (int i = 0; …
```
=> Make group lookup function for user

c/collections.c, c/httpserver.c, h/httpserver.h, h/zosaccounts.h
This makes use of recent PRs https://github.com/zowe/zowe-common-c/pull/192 and https://github.com/zowe/zowe-common-c/pull/190 in order to set cookie timeout according to the user or group the user is in. In the case that a user is specified in the list, that value is chosen. In the case the user is not found in the list, groups are checked. If a user is in multiple groups found, the longest session duration value is chosen. If the value is -1, that means there is no expiration. 0 is considered not found, and when not found, the default value (1 hour) will be chosen.
Because the cookie doesnt and shouldnt contain info such as expiration, and because the cookie is given during any call, a header is needed for sending expiration information.
I did not find any standard or non-standard …
=> Check and return variable session timeout info

c/stcbase.c
Function `zosPost` is not properly declared in `c/stcbase.c`, this may lead to unexpected behavior where the compiler assumes that the arguments are all `int`s whereas we need to pass a 64-bit address and an int. This pull-request include `scheduling.h` to ensure the compiler knows the `zosPost` prototype.
=> Fix an implicit declaration

c/http.c
When an additional check was introduced (EWOULDBLOCK), the WRITE_FORCE
value was not correctly applied - it should be AND'ed with both the
EAGAIN and EWOULDBLOCK values:
`WRITE_FORCE and (EAGAIN or EWOULDBLOCK)`
=> Fix an incorrect if condition in the http socket write function

c/httpserver.c
Various problems fixed: int initialization, using int instead of uint64, and not checking retval before acting upon returned values.
=> Fixed bugs around the value for session timeout

CHANGELOG.md, c/httpserver.c
ZSS never set options on its cookies, and app-server would to some extent add options or hide the cookie from the browser, such that any potential issues of the zss cookie was hidden.
But, with HA/FT work, it's important to get the cookie up to the browser, and here is where I see an issue:
If a server doesnt set a path property for a cookie, browsers will add one relative to the path of the request. But, because zss will give you a new cookie every time you call (refreshing the cookie), it means the browser may end up holding 10 different zss cookies because it tracks by paths it made up.
The solution is just to explicitly set path to root, so that the browser just has 1 cookie, which is what we want.
=> Set cookie path

c/httpclient.c
This PR allows to handle correctly statuses with empty status message e.g. `HTTP/1.1 404` (compare with `HTTP/1.1 404 Not Found` which has non empty status message)
=> HTTP Client: Handle empty status string

c/datasetjson.c
Fix for dataset write when recfm=FB. The code mistakenly called `safeFree()` for memory allocated in `ShortLivedHeap`.
PR for testing: https://github.com/zowe/zss/pull/276
=> Fix for dataset write when recfm=FB

c/tls.c
Increase minimum server Diffie-Hellman group size that is allowed for an ephemeral Diffie-Hellman key exchange message.
=> Increase minimum server Diffie-Hellman group size that is allowed for an ephemeral Diffie-Hellman key exchange message.

c/tls.c
Increase minimum server Diffie-Hellman group size that is allowed for an ephemeral Diffie-Hellman key exchange message.
=> Increase DH key size

CHANGELOG.md, c/httpserver.c
This PR fixes a bug when downloading hangs for empty file with binary tag or without tags.
=> Unix-file contents: Properly handle empty files

c/crossmemory.c, c/recovery.c, h/crossmemory.h, h/zowetypes.h
Here's my initial adjustments for the ZSS 64 changes.
* Minor changes in cross-memory
* Make the new ABEND diagnostics a compile-time option in recovery.c
* Revert whitespace changes
* Revert `bool` to be `int` to keep compatibility with the existing plugins/structures
More work may be needed in recovery, zos and radmin.
=> Updates for feature/zss64_2021

c/httpserver.c
Even though we have logic to close the connection, we aren't using it. I'd like to reinstate the code that was removed temporarily, unless there are any objections.
It goes along with the changes added in this pull request: https://github.com/zowe/zowe-common-c/commit/6cbd244f2147be5e653773ab9bc457cab628c141
=> Reinstating keep-alive

c/httpserver.c
With conditionally backward-compatible behavior, this adds new parameters to the zss cookie to meet best practices in  modern browsers.
=> Add cookie properties

c/tls.c
This PR fixes a bug when TLS socket wasn't closed. For example, if connection was closed by peer then `gsk_secure_socket_shutdown()` retuned non zero, therefore a call to `gsk_secure_socket_close()` didn't happen. This fix removes unnecessary call to  `gsk_secure_socket_shutdown()`
=> Always close TLS socket

jwt/rscrypto/rs_icsfp11.c, jwt/rscrypto/rs_icsfp11.h
This PR fixes JWT for 64-bit mode. CK_ULONG is 8 bytes in 64 bit mode, but we needed only 4 bytes so I replaced it with `unsigned int` as in other places.
=> Fix JWT for 64-bit mode

c/httpfileservice.c, h/httpfileservice.h
Signed-off-by: Aditya Ranshinge <aranshinge@rocketsoftware.com>
This PR fixes a bug to return valid status for POST /unixfile/copy/{directory}/{file} and POST /unixfile/copy/{directory}
Defined new error codes in httpfileservice.h to identify multiple error scenarios like Bad Request, Not Found, Forbidden etc.
Identified errors in copyUnixFile() and copyUnixDirectory().
Added error tracing logic in copyUnixDirectoryAndRespond() and copyUnixFileAndRespond().
Updated error strings accordingly.
=> Updated unixfile/copy return status

c/httpserver.c
This PR hides `auth extraction function returns 0!` message under DEBUG trace level.
=> Hide "auth extraction function returns 0!" message under DEBUG trace level

c/httpfileservice.c, h/httpfileservice.h
Signed-off-by: Aditya Ranshinge <aranshinge@rocketsoftware.com>
This PR fixes a bug to allow forceOverwrite directories for rename and copy Unixfile API and return valid status for POST /unixfile/rename/{directory}
Used existing error codes defined in httpfileservice.h to identify multiple error scenarios like Bad Request, Not Found, Forbidden etc.
If forceOverwrite query is true and newName already exists then existing dir is deleted.
=> resolved forceOverwrite dir and updated return errors of rename dir

CHANGELOG.md, c/zosfile.c
This PR fixes the Unixfile copy service for files tagged as binary and mixed.
The service couldn't copy binary files and incorrectly tagged mixed files as text. Now the service correctly copies such files.
=> Fix Unixfile copy service for files tagged as binary and mixed

c/datasetjson.c
Prevent writing to dataset types that are inappropriate for the /datasetContents API, or have not been properly tested yet.
We may relax these restrictions in the future if we learn it is safe to use this API for writing, but this is just an initial set of preventing things that do not seem safe to do. This logic is largely based on DSORG checks, but also not allowing writes to PDSs instead of their members.
=> Write dataset type validation

CHANGELOG.md, c/dataservice.c
This PR introduces support for `libraryName31` and `libraryName64` keys for dataService. The keys allow to distinguish 31 and 64-bit versions of a plugin. If bits-specific key not found then zss tries to load the dll using `libraryName` key. For example,
```json
{
"identifier": "org.zowe.my.plugin",
"apiVersion": "1.0.0",
"pluginVersion": "1.2.1",
"pluginType": "application",
"dataServices": [
{
"type": "service",
"name": "myService",
"libraryName31": "myService31.so",
"libraryName64": "myService64.so",
"dependenciesIncluded": true,
"methods": [ "GET", "POST", "DELETE" ],
"initializerName": "myServiceServiceInstaller",
"initializerLookupMethod": "external",
"version": "0.0.1"
}
]
}
```
=> Support for libraryName31 and libraryName64 keys for dataServices in pluginDefinition.json

c/crossmemory.c, h/crossmemory.h, h/zos.h
The main purpose of this PR is to the ability to run ZIS using any module name. Right now, ZIS makes some assumptions about its module name. Additionally, the PR fixes a bug in the service address check function when ZIS is run using an alias.
* `RC_CMS_PC_NOT_IMPLEMENTED` was not used, so its number got recycled
* The log level initialization has been moved to be done earlier so that we can print debug info in the `getCurrentModuleName` function
=> ZIS custom module name
